config/routes.rb
Splitzies::Application.routes.draw do
  resources :roommate_notifications do
    match 'seen', as: :see, on: :member
    match 'clear', on: :collection
  end

  get '/users/friends' => 'users#friends', as: :invite_friends
  match '/users/next_step' => 'users#next_step', as: :next_step

  resources :expenses do
    put 'recover', on: :member
  end

  resources :households
  resources :invites, :only => [ :create, :show, :update ]
  resources :roommates, path: 'users', controller: :users

  resources :sessions, only: [:create, :index]

  match '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#logout', as: 'logout'
  root :to => 'sessions#new', as: 'login'
end

app/models/roommate_notification.rb
class RoommateNotification < ActiveRecord::Base
  attr_accessible :notification_id, :roommate_id, :seen_at
  belongs_to :notification
  belongs_to :roommate

  default_scope where(seen_at: nil)

  def seen!
    self.update_attribute :seen_at, Time.new
  end

  def seen?
    ! seen_at.nil?
  end
end

app/controllers/roommate_notifications_controller.rb
class RoommateNotificationsController < ApplicationController
  def seen
    @roommate_notification = RoommateNotification.find params[:id]
    @roommate_notification.seen!

    respond_to do |format|
      format.json { render json: @roommate_notification }
      format.html { redirect_to @roommate_notification.notification.axis }
    end
  end

  def clear
    @roommate_notifications = current_user.roommate_notifications.each(&:seen!)

    respond_to do |format|
      format.json { render json: @roommate_notifications }
      format.html { redirect_to request.referrer }
    end
  end

  # GET /roommate_notifications
  # GET /roommate_notifications.json
  def index
    @roommate_notifications = RoommateNotification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roommate_notifications }
    end
  end

  # GET /roommate_notifications/1
  # GET /roommate_notifications/1.json
  def show
    @roommate_notification = RoommateNotification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roommate_notification }
    end
  end

  # GET /roommate_notifications/new
  # GET /roommate_notifications/new.json
  def new
    @roommate_notification = RoommateNotification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roommate_notification }
    end
  end

  # GET /roommate_notifications/1/edit
  def edit
    @roommate_notification = RoommateNotification.find(params[:id])
  end

  # POST /roommate_notifications
  # POST /roommate_notifications.json
  def create
    @roommate_notification = RoommateNotification.new(params[:roommate_notification])

    respond_to do |format|
      if @roommate_notification.save
        format.html { redirect_to @roommate_notification, notice: 'Roommate notification was successfully created.' }
        format.json { render json: @roommate_notification, status: :created, location: @roommate_notification }
      else
        format.html { render action: "new" }
        format.json { render json: @roommate_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roommate_notifications/1
  # PUT /roommate_notifications/1.json
  def update
    @roommate_notification = RoommateNotification.find(params[:id])

    respond_to do |format|
      if @roommate_notification.update_attributes(params[:roommate_notification])
        format.html { redirect_to @roommate_notification, notice: 'Roommate notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roommate_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roommate_notifications/1
  # DELETE /roommate_notifications/1.json
  def destroy
    @roommate_notification = RoommateNotification.find(params[:id])
    @roommate_notification.destroy

    respond_to do |format|
      format.html { redirect_to roommate_notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roommate_notifications_helper.rb
module RoommateNotificationsHelper
end

app/views/roommate_notifications/_expense.html.haml
#{notification.roommate == current_user ? "You" : notification.roommate.full_name} #{notification.action} an expense for #{expense.item_name}.

app/views/roommate_notifications/_form.html.erb
<%= simple_form_for(@roommate_notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roommate_notifications/_roommate_notification.html.haml
%li{ class: "notification #{roommate_notification.seen? ? "seen" : "unseen" }", :'data-id' => roommate_notification.id }
  = link_to roommate_notification.notification.axis do
    = render partial: "roommate_notifications/#{roommate_notification.notification.axis_type.underscore}", locals: { notification: roommate_notification.notification, roommate_notification: roommate_notification, :"#{roommate_notification.notification.axis_type.underscore}" => roommate_notification.notification.axis }

app/views/roommate_notifications/edit.html.erb
<h1>Editing roommate_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @roommate_notification %> |
<%= link_to 'Back', roommate_notifications_path %>

app/views/roommate_notifications/index.html.erb
<h1>Listing roommate_notifications</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roommate_notifications.each do |roommate_notification| %>
  <tr>
    <td><%= link_to 'Show', roommate_notification %></td>
    <td><%= link_to 'Edit', edit_roommate_notification_path(roommate_notification) %></td>
    <td><%= link_to 'Destroy', roommate_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Roommate notification', new_roommate_notification_path %>

app/views/roommate_notifications/new.html.erb
<h1>New roommate_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', roommate_notifications_path %>

app/views/roommate_notifications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_roommate_notification_path(@roommate_notification) %> |
<%= link_to 'Back', roommate_notifications_path %>