config/routes.rb
Splitzies::Application.routes.draw do
  resources :roommate_notifications do
    match 'seen', as: :see, on: :member
    match 'clear', on: :collection
  end

  get '/users/friends' => 'users#friends', as: :invite_friends
  match '/users/next_step' => 'users#next_step', as: :next_step

  resources :expenses do
    put 'recover', on: :member
  end

  resources :households
  resources :invites, :only => [ :create, :show, :update ]
  resources :roommates, path: 'users', controller: :users

  resources :sessions, only: [:create, :index]

  match '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#logout', as: 'logout'
  root :to => 'sessions#new', as: 'login'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_filter :must_be_logged_in

  def recover
    @expense = Expense.with_deleted.find(params[:id]) rescue nil

    respond_to do |format|
      unless @expense.nil?
        if @expense.deleted? && @expense.recover
          Notification.notify!(@expense.roommates, current_user, :recovered, @expense)
          format.html { redirect_to @expense, notice: "This expense has been restored" }
          format.json { render json: @expense }
        else
          format.html { render :edit }
          format.json { render json: @expense }
        end
      else
        format.html { redirect_to expenses_path, status: :not_found }
        format.json { render nothing: true, status: :not_found }
      end
    end
  end

  def index
    @household = current_user.household
    @expenses = @household.expenses
    @roommates = @household.roommates
    @max_expenses = @roommates.reduce do |r2, r1|
      c1 = r1.expenses.count
      c2 = r2.is_a?(Roommate) ? r2.expenses.count : r2
      c1 > c2 ? c1 : c2
    end
    @expense = @household.expenses.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  def show
    @expense = Expense.with_deleted.find(params[:id])
    @expense.notifications.seen_by!(current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = current_user.household.expenses.new(
      created_by_roommate_id: current_user.id,
      roommate_id: current_user.id
    )

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    roommates = params[:expense][:roommate_expenses]
    params[:expense].delete :roommate_expenses
    @expense = Expense.create params[:expense]

    roommates.values.each { |r|
      @expense.roommate_expenses.new(r)
    }

    respond_to do |format|
      if @expense.save
        Notification.notify!(@expense.roommates, current_user, :created, @expense)
        format.html { redirect_to expenses_path, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    roommates = params[:expense][:roommate_expenses]
    params[:expense].delete :roommate_expenses
    @expense = Expense.find(params[:id])
    @expense.update_attributes params[:expense]
    roommates.values.each { |r|
      re = RoommateExpense.find r['id']
      re.update_attributes r
    }

    Notification.notify! @expense.roommates, current_user, :edited, @expense

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to expenses_path, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    Notification.notify!(@expense.roommates, current_user, :deleted, @expense)

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.haml
= simple_form_for(@expense, html: { class: 'form-inline' }) do |f|
  - if @expense.errors.any?
    #error_explanation
      %h2
        = pluralize(@expense.errors.count, "error")
        prohibited this expense from being saved:
      %ul
        - @expense.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :household_id
  = f.hidden_field :id
  = f.hidden_field :created_by_roommate_id
  .field.clearfix#expense-madlib
    .input-prepend.inline
      = content_tag :span, '$', class: 'add-on abbn'
      = f.input_field :value, placeholder: '100.00'
    = f.input_field :paid_in, collection: { :'spent on' => true, :'paid into the pool for' => false }, prompt: false, label: false
    = f.input_field :item_name, label: false, placeholder: 'butter, eggs, gas...'
    %label.by by
    = f.input_field :roommate_id, collection: @expense.household.roommates.collect { |u| ["#{u.first_name} #{u.last_name}", u.id] }, prompt: false, label: false
    = f.input_field :split_evenly, checked: 'checked'
    %label split evenly
  %fieldset.control-group
    %legend= f.label 'Between'
    .controls#select_roommates_widget
      - @expense.household.roommates.each do |roommate|
        = simple_fields_for :"expense[roommate_expenses][#{roommate.id}]", (roommate_expense = (roommate.roommate_expenses.find_by_expense_id(@expense.id) || roommate.roommate_expenses.new)) do |ref|
          %div{ class: "field clearfix pull-left roommate-checkbox#{roommate_expense.included? ? ' active' : ''}" }
            = ref.hidden_field :id
            = ref.hidden_field :roommate_id
            = ref.hidden_field :expense_id
            = ref.hidden_field :included, class: 'included'
            .user-image
              = image_tag roommate.photo(:square)
            %label=roommate.full_name
  .control-group
    = f.label 'Add a note'
    .controls
      = f.text_area :note, rows: 5, cols: 100
  .actions
    = f.submit

app/views/expenses/edit.html.haml
%h1 Editing expense
= render 'form'
= link_to 'Show', @expense
|
\#{link_to 'Back', expenses_path}

app/views/expenses/index.html.haml
%h1 Shared expenses for #{current_user.household.nickname}
.row#expenses_table
  .span3
    %h4 Create an Expense
    .well
      = render 'form'

  .span9
    #expenses_table__container
      %table.table
        %thead
          %tr
            - @roommates.each do |r|
              %th{ class: "column-#{@roommates.index(r) % 2 == 0 ? 'even' : 'odd'}" }
                #{r.full_name}
        %tbody
          - (0..@max_expenses - 1).each do |index|
            %tr
              - @roommates.each do |r|
                %td{ class: "column-#{index % 2 == 0 ? 'even' : 'odd'} row-#{@roommates.index(r) % 2 == 0 ? 'even' : 'odd'}" }
                  - unless (expense = r.expenses[index]).nil?
                    <span class="item_name" contenteditable="false">#{expense.item_name}</span>: $<span class="item_value" contenteditable="false">#{expense.value}</span>
                    %p <span class="light">#{expense.note}</span> #{link_to "edit", edit_expense_path(expense)}

        %tfoot
          %tr
            - @roommates.each do |r|
              %td
                - if r.cash_owed.nil?
                  No balance
                - else
                  #{r.cash_owed > 0 ? 'Owes ' : 'Owed '} $#{to_money(r.cash_owed).abs}
    %br/
    = link_to 'Invite More Roommates', invite_friends_path, class: 'btn btn-custom btn-primary btn-small'

app/views/expenses/new.html.haml
%h1 New expense
= render 'form'
= link_to 'Back', expenses_path

app/views/expenses/show.html.haml
%p#notice= notice

- if @expense.deleted?
  %p
    %b
      This expense has been deleted.
      It will not be included in the net owed. 
      #{link_to "Recover it", recover_expense_path(@expense), method: :put}.
%p
  %b Household:
  = @expense.household.nickname
%p
  = @expense.roommate.full_name
  = @expense.paid_in ? 'spent' : 'paid in'
  $
  = @expense.value
  = "split evenly #{@expense.household.roommates.count} ways" if @expense.split_evenly
  for
  = @expense.item_name
- if @expense.note != ''
  %p
    Other Notes:
  %p
    = @expense.note

= link_to 'Edit', edit_expense_path(@expense)
|
\#{link_to 'Back', expenses_path}