config/routes.rb
Splitzies::Application.routes.draw do
  resources :roommate_notifications do
    match 'seen', as: :see, on: :member
    match 'clear', on: :collection
  end

  get '/users/friends' => 'users#friends', as: :invite_friends
  match '/users/next_step' => 'users#next_step', as: :next_step

  resources :expenses do
    put 'recover', on: :member
  end

  resources :households
  resources :invites, :only => [ :create, :show, :update ]
  resources :roommates, path: 'users', controller: :users

  resources :sessions, only: [:create, :index]

  match '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#logout', as: 'logout'
  root :to => 'sessions#new', as: 'login'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Splitzies
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    .navbar.navbar-static-top#primary
      .navbar-inner
        .container
          .brand Splitzies
          - unless current_user.nil?
            %ul.nav.pull-right
              %li=link_to 'Expenses', expenses_path
              - unless current_user.roommate_notifications.empty?
                %li.dropdown#notifications-dropdown
                  =link_to 'javascript:void(0)', :class => 'dropdown-toggle', :'data-toggle' => :dropdown do
                    %i.icon-list.icon-white
                  %ul.dropdown-menu
                    - current_user.roommate_notifications.sort_by { |rn| 0 - rn.created_at.to_i }.each do |rn|
                      = render rn
                    %li
                      = link_to clear_roommate_notifications_path do
                        %i.icon-remove
                        Clear Notifications
              %li.dropdown#current-user-dropdown
                = link_to 'javascript:void(0)', :class => 'dropdown-toggle', :'data-toggle' => :dropdown do
                  = image_tag current_user.photo
                  = current_user.full_name
                %ul.dropdown-menu
                  %li=link_to "Account Settings", edit_roommate_path(current_user)
                  %li=link_to 'Log out', logout_path
    .container
      = yield
    #fb-root
    %script{:src => "http://connect.facebook.net/en_US/all.js"}
    :javascript
      FB.init({
        appId: '#{ENV['FACEBOOK_KEY']}'
      });
    = javascript_include_tag "application"

app/views/layouts/notification_mailers.html.haml
= yield

%p= link_to "Manage Email Preferences", edit_roommate_url(@user)