config/routes.rb
Splitzies::Application.routes.draw do
  resources :roommate_notifications do
    match 'seen', as: :see, on: :member
    match 'clear', on: :collection
  end

  get '/users/friends' => 'users#friends', as: :invite_friends
  match '/users/next_step' => 'users#next_step', as: :next_step

  resources :expenses do
    put 'recover', on: :member
  end

  resources :households
  resources :invites, :only => [ :create, :show, :update ]
  resources :roommates, path: 'users', controller: :users

  resources :sessions, only: [:create, :index]

  match '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#logout', as: 'logout'
  root :to => 'sessions#new', as: 'login'
end

app/models/household.rb
class Household < ActiveRecord::Base
  attr_accessible :nickname

  has_many :roommates
  has_many :expenses
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # GET /households
  # GET /households.json
  def index
    @households = Household.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @households }
    end
  end

  # GET /households/1
  # GET /households/1.json
  def show
    @household = Household.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/new
  # GET /households/new.json
  def new
    @household = Household.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.json
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        current_user.update_attribute :household_id, @household.id
        format.html { redirect_to next_step_path }
        format.json { render json: @household, status: :created, location: @household }
      else
        format.html { render action: "new" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.json
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.json
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to households_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_form.html.erb
<%= form_for(@household) do |f| %>
  <% if @household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/households/edit.html.erb
<h1>Editing household</h1>

<%= render 'form' %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<h1>Listing households</h1>

<table>
  <tr>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @households.each do |household| %>
  <tr>
    <td><%= household.nickname %></td>
    <td><%= link_to 'Show', household %></td>
    <td><%= link_to 'Edit', edit_household_path(household) %></td>
    <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Household', new_household_path %>

app/views/households/new.html.erb
<h1>Start off by setting up your household</h1>

<%= render 'form' %>

app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nickname:</b>
  <%= @household.nickname %>
</p>


<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>